#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDF_Invites
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Stratadial")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::PDF_Invites.Properties.Settings.Default.StratadialConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<JB_INVITE> JB_INVITEs
		{
			get
			{
				return this.GetTable<JB_INVITE>();
			}
		}
		
		public System.Data.Linq.Table<JB_INVITE_TRACKER> JB_INVITE_TRACKERs
		{
			get
			{
				return this.GetTable<JB_INVITE_TRACKER>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.JB_INVITE")]
	public partial class JB_INVITE
	{
		
		private int _id;
		
		private string _Meeting_Coordinator;
		
		private string _NFP_Code_Janssen_ID;
		
		private string _Topic;
		
		private string _DomeManager;
		
		private string _PriorityDriver;
		
		private string _Type_of_Program;
		
		private string _Time;
		
		private string _Zone;
		
		private string _LDC;
		
		private string _LDCCellPhone;
		
		private string _DM;
		
		private string _RequestReceived;
		
		private string _Confirmed_Event_Date;
		
		private string _ProgramPending;
		
		private string _IfCancelled;
		
		private string _ifCancelled2;
		
		private string _ifCancelled3;
		
		private string _ProgramStatusNotes;
		
		private string @__1stChoice;
		
		private string @__2ndChoice;
		
		private string @__3rdChoice;
		
		private string _ConfirmedSpeaker;
		
		private string @__1stChoiceDate;
		
		private System.Nullable<decimal> _Air;
		
		private System.Nullable<decimal> _Hotel;
		
		private System.Nullable<decimal> _Ground;
		
		private System.Nullable<decimal> _Speaker_Fee;
		
		private string _Speaker_Fee_Date;
		
		private System.Nullable<decimal> _Travel_Expense;
		
		private string _Travel_Expense_Date;
		
		private string _VenueName;
		
		private string _VenueAddress1;
		
		private string _VenueAddress2;
		
		private string _VenueCity;
		
		private string _VenueState;
		
		private string _VenueZip;
		
		private string _VenuePhone;
		
		private string _VenueContact;
		
		private string _HEadCount;
		
		private System.Nullable<decimal> _Total_F_B;
		
		private System.Nullable<decimal> _RoomCharge;
		
		private System.Nullable<decimal> _VenueA_VCost;
		
		private System.Nullable<decimal> _A_V;
		
		private string _InvitationPDFUploaded;
		
		private string _AdditionalReqMeetingDate;
		
		private string _DomeManagerCellPhone;
		
		private System.Nullable<decimal> _Parking;
		
		private System.Nullable<decimal> _Accounting;
		
		private string _invite_qty;
		
		private System.Nullable<decimal> _Invite;
		
		private System.Nullable<decimal> _Fed_Ex;
		
		private string _WebEventifCancelled1;
		
		private System.Nullable<decimal> _WebExpense;
		
		private System.Nullable<decimal> _WebProduction;
		
		private string _ThirdRequestDate;
		
		private System.Nullable<decimal> _Event_Mgt_Svcs;
		
		private string _Meal;
		
		private string _Presentation_Title;
		
		private string _preconfirmed_speaker;
		
		private string _preconfirmed_meeting_date;
		
		private string _Financial_Notes;
		
		private string _program_details_upload;
		
		private string _attendee_upload;
		
		private string _speaker_upload;
		
		private string _Apex_Job_Number;
		
		private System.Nullable<decimal> _Check_Number_Fee;
		
		private System.Nullable<decimal> _Check_Number_Travel;
		
		private System.Nullable<decimal> _Number_of_rehearsals;
		
		private System.Nullable<System.DateTime> _OIG_Check_date_speaker_bureau;
		
		private System.Nullable<System.DateTime> _EPLS_Check_date_speaker_bureau;
		
		private string _FDAdebarment_speaker_bureau;
		
		private string _Region;
		
		private string _If_cancelled__Travel1;
		
		private string _If_cancelled__Travel2;
		
		private string _If_cancelled__Travel3;
		
		private string _Any_reason_for_cancel1;
		
		private string _Invitations_Mailed;
		
		private string _invite_qty2;
		
		private System.Nullable<decimal> _invite2;
		
		private string _Dual_Speaker;
		
		private string _Dual_Speaker_Fee;
		
		private string _Dual_Speaker_Expenses;
		
		private string _Dual_Speaker_Air;
		
		private string _Dual_Speaker_Hotel;
		
		private string _Dual_Speaker_Ground;
		
		private string @__4thChoiceDate;
		
		private string @__4thchoicespeaker;
		
		private string @__5thchoicespeaker;
		
		private string _dualspeakerfeedateoncheck;
		
		private string _dualspeakerexpensesdateoncheck;
		
		private string _dualspeakerfeechecknumber;
		
		private string _dualspeakerexpenseschecknumber;
		
		private System.Nullable<decimal> _Grand_Total_F_B;
		
		private System.Nullable<decimal> _Grand_Total_Speaker;
		
		private System.Nullable<decimal> _Invitation_Total;
		
		private System.Nullable<decimal> _Web_Total;
		
		private System.Nullable<decimal> _Total_Change_Costs;
		
		private System.Nullable<decimal> _Total_Cancellation_Costs;
		
		private System.Nullable<System.DateTime> _Last_Edited;
		
		private string _All_Costs_for_Program_Entered;
		
		private string _Totality_Uploaded;
		
		private string _LDC_Phone;
		
		private string _LDC_Email;
		
		private System.Nullable<decimal> _venue_cancellation_fee;
		
		private System.Nullable<decimal> _CWT_Transaction_Fee;
		
		private string _CWT_Transaction_Fee_Changes;
		
		private System.Nullable<decimal> _Train_Expense;
		
		private System.Nullable<decimal> _CWT_Transaction_Fee_Ground;
		
		private System.Nullable<decimal> _CWT_Transaction_Fee_Hotel;
		
		private string _CWT_Transaction_Fee_Changes_Ground;
		
		private string _CWT_Transaction_Fee_Changes_Hotel;
		
		private System.Nullable<decimal> _CWT_Transaction_Fee_Total;
		
		private string _Confirmed_Speaker_Phone;
		
		private string _Confirmed_Speaker_Email;
		
		private string _Venue_Receipt_Received;
		
		private System.Nullable<System.DateTime> _Attendee_Checklist_Received;
		
		private System.Nullable<decimal> _Attendees_served;
		
		private System.Nullable<decimal> _Cost_per_attendee;
		
		private string _Totalityneeded;
		
		private System.Nullable<System.DateTime> _signinsheetuploaded;
		
		private System.Nullable<System.DateTime> _folder_received;
		
		private string _totality_completed_by;
		
		private string _cancel_email_requested;
		
		private string _CardRequested;
		
		private string _CardNumber;
		
		private string _CardImage;
		
		private string _CardImageBack;
		
		private string _EndTime;
		
		private string _EndTimeZone;
		
		private string _apex_fax_number;
		
		private string _DMTitle;
		
		private string _checkrequest;
		
		private string _Booked_via_Get_There;
		
		private string _Dual_Speaker_Phone;
		
		private string _Dual_Speaker_Email;
		
		private string _CWT2_Transaction_Fee_Changes_Ground;
		
		private string _CWT2_Transaction_Fee_Changes;
		
		private System.Nullable<decimal> _CWT2_Transaction_Fee_Ground;
		
		private System.Nullable<decimal> _CWT2_Transaction_Fee_Total;
		
		private System.Nullable<decimal> _CWT2_Transaction_Fee;
		
		private string _domelink;
		
		private string _vipdialin;
		
		private string _participantdialin;
		
		private string _inviteprint2;
		
		private string _inviteprint3;
		
		private string _domemgremail;
		
		private string _Presentation_Time;
		
		private string _Meal_and_Presentation_Type;
		
		private System.Nullable<System.DateTime> _Confirmed_Date_for_Invite;
		
		private string _WebEventifCancelled2;
		
		private string _WebEventifCancelled3;
		
		private string _Any_reason_for_cancel2;
		
		private string _Any_reason_for_cancel3;
		
		private System.Nullable<decimal> _Totality;
		
		private System.Nullable<decimal> _CWT2_Transaction_Fee_Hotel;
		
		private string _CWT2_Transaction_Fee_Changes_Hotel;
		
		private string @__2ndChoiceDate;
		
		private string @__3rdChoiceDate;
		
		private System.Nullable<decimal> _Service_Vendor_Fee;
		
		private string _inviteprint1;
		
		private string _ConfirmedSpeakerDate;
		
		private string _franchise;
		
		private string _meeting_format;
		
		private string _meal_type;
		
		private string _location_type;
		
		private string _non_compliant_venue;
		
		private string _venue_contact_email;
		
		private string _fedex_tracking_invitations;
		
		private string _fedex_tracking_in_office;
		
		private System.Nullable<System.DateTime> _date_in_office_shipment_mailed;
		
		private string _additional_shipments_notes;
		
		private string _unmet_minimum;
		
		private string _no_of_guaranteed_attendees;
		
		private string _fedex_tracking_speaker_fee;
		
		private string _fedex_tracking_speaker_expense;
		
		private System.Nullable<System.DateTime> _date_submitted_for_totality;
		
		private string _fedex_tracking_speaker_fee_rheum;
		
		private string _fedex_tracking_speaker_expense_rheum;
		
		private string _fedex_tracking_dual_speaker_fee;
		
		private string _fedex_tracking_dual_speaker_expense;
		
		private string _based_on_guarantee;
		
		private string _QC_By;
		
		private System.Nullable<System.DateTime> _QC_Date;
		
		private System.Nullable<decimal> _Total_restaurant_catering_receipt;
		
		public JB_INVITE()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Meeting Coordinator]", Storage="_Meeting_Coordinator", DbType="NVarChar(50)")]
		public string Meeting_Coordinator
		{
			get
			{
				return this._Meeting_Coordinator;
			}
			set
			{
				if ((this._Meeting_Coordinator != value))
				{
					this._Meeting_Coordinator = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[NFP Code/Janssen ID]", Storage="_NFP_Code_Janssen_ID", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string NFP_Code_Janssen_ID
		{
			get
			{
				return this._NFP_Code_Janssen_ID;
			}
			set
			{
				if ((this._NFP_Code_Janssen_ID != value))
				{
					this._NFP_Code_Janssen_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Topic", DbType="NVarChar(500)")]
		public string Topic
		{
			get
			{
				return this._Topic;
			}
			set
			{
				if ((this._Topic != value))
				{
					this._Topic = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DomeManager", DbType="NVarChar(100)")]
		public string DomeManager
		{
			get
			{
				return this._DomeManager;
			}
			set
			{
				if ((this._DomeManager != value))
				{
					this._DomeManager = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PriorityDriver", DbType="NVarChar(50)")]
		public string PriorityDriver
		{
			get
			{
				return this._PriorityDriver;
			}
			set
			{
				if ((this._PriorityDriver != value))
				{
					this._PriorityDriver = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Type of Program]", Storage="_Type_of_Program", DbType="NVarChar(50)")]
		public string Type_of_Program
		{
			get
			{
				return this._Type_of_Program;
			}
			set
			{
				if ((this._Type_of_Program != value))
				{
					this._Type_of_Program = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Time", DbType="NVarChar(50)")]
		public string Time
		{
			get
			{
				return this._Time;
			}
			set
			{
				if ((this._Time != value))
				{
					this._Time = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zone", DbType="NVarChar(50)")]
		public string Zone
		{
			get
			{
				return this._Zone;
			}
			set
			{
				if ((this._Zone != value))
				{
					this._Zone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LDC", DbType="NVarChar(100)")]
		public string LDC
		{
			get
			{
				return this._LDC;
			}
			set
			{
				if ((this._LDC != value))
				{
					this._LDC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LDCCellPhone", DbType="NVarChar(50)")]
		public string LDCCellPhone
		{
			get
			{
				return this._LDCCellPhone;
			}
			set
			{
				if ((this._LDCCellPhone != value))
				{
					this._LDCCellPhone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DM", DbType="NVarChar(100)")]
		public string DM
		{
			get
			{
				return this._DM;
			}
			set
			{
				if ((this._DM != value))
				{
					this._DM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RequestReceived", DbType="NVarChar(50)")]
		public string RequestReceived
		{
			get
			{
				return this._RequestReceived;
			}
			set
			{
				if ((this._RequestReceived != value))
				{
					this._RequestReceived = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Confirmed Event Date]", Storage="_Confirmed_Event_Date", DbType="NVarChar(50)")]
		public string Confirmed_Event_Date
		{
			get
			{
				return this._Confirmed_Event_Date;
			}
			set
			{
				if ((this._Confirmed_Event_Date != value))
				{
					this._Confirmed_Event_Date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProgramPending", DbType="NVarChar(50)")]
		public string ProgramPending
		{
			get
			{
				return this._ProgramPending;
			}
			set
			{
				if ((this._ProgramPending != value))
				{
					this._ProgramPending = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IfCancelled", DbType="NVarChar(500)")]
		public string IfCancelled
		{
			get
			{
				return this._IfCancelled;
			}
			set
			{
				if ((this._IfCancelled != value))
				{
					this._IfCancelled = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ifCancelled2", DbType="NVarChar(500)")]
		public string ifCancelled2
		{
			get
			{
				return this._ifCancelled2;
			}
			set
			{
				if ((this._ifCancelled2 != value))
				{
					this._ifCancelled2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ifCancelled3", DbType="NVarChar(500)")]
		public string ifCancelled3
		{
			get
			{
				return this._ifCancelled3;
			}
			set
			{
				if ((this._ifCancelled3 != value))
				{
					this._ifCancelled3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProgramStatusNotes", DbType="NVarChar(MAX)")]
		public string ProgramStatusNotes
		{
			get
			{
				return this._ProgramStatusNotes;
			}
			set
			{
				if ((this._ProgramStatusNotes != value))
				{
					this._ProgramStatusNotes = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[1stChoice]", Storage="__1stChoice", DbType="NVarChar(200)")]
		public string _1stChoice
		{
			get
			{
				return this.@__1stChoice;
			}
			set
			{
				if ((this.@__1stChoice != value))
				{
					this.@__1stChoice = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[2ndChoice]", Storage="__2ndChoice", DbType="NVarChar(200)")]
		public string _2ndChoice
		{
			get
			{
				return this.@__2ndChoice;
			}
			set
			{
				if ((this.@__2ndChoice != value))
				{
					this.@__2ndChoice = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[3rdChoice]", Storage="__3rdChoice", DbType="NVarChar(200)")]
		public string _3rdChoice
		{
			get
			{
				return this.@__3rdChoice;
			}
			set
			{
				if ((this.@__3rdChoice != value))
				{
					this.@__3rdChoice = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ConfirmedSpeaker", DbType="NVarChar(200)")]
		public string ConfirmedSpeaker
		{
			get
			{
				return this._ConfirmedSpeaker;
			}
			set
			{
				if ((this._ConfirmedSpeaker != value))
				{
					this._ConfirmedSpeaker = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[1stChoiceDate]", Storage="__1stChoiceDate", DbType="NVarChar(50)")]
		public string _1stChoiceDate
		{
			get
			{
				return this.@__1stChoiceDate;
			}
			set
			{
				if ((this.@__1stChoiceDate != value))
				{
					this.@__1stChoiceDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Air", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Air
		{
			get
			{
				return this._Air;
			}
			set
			{
				if ((this._Air != value))
				{
					this._Air = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hotel", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Hotel
		{
			get
			{
				return this._Hotel;
			}
			set
			{
				if ((this._Hotel != value))
				{
					this._Hotel = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ground", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Ground
		{
			get
			{
				return this._Ground;
			}
			set
			{
				if ((this._Ground != value))
				{
					this._Ground = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Speaker Fee]", Storage="_Speaker_Fee", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Speaker_Fee
		{
			get
			{
				return this._Speaker_Fee;
			}
			set
			{
				if ((this._Speaker_Fee != value))
				{
					this._Speaker_Fee = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Speaker Fee Date]", Storage="_Speaker_Fee_Date", DbType="NVarChar(50)")]
		public string Speaker_Fee_Date
		{
			get
			{
				return this._Speaker_Fee_Date;
			}
			set
			{
				if ((this._Speaker_Fee_Date != value))
				{
					this._Speaker_Fee_Date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Travel Expense]", Storage="_Travel_Expense", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Travel_Expense
		{
			get
			{
				return this._Travel_Expense;
			}
			set
			{
				if ((this._Travel_Expense != value))
				{
					this._Travel_Expense = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Travel Expense Date]", Storage="_Travel_Expense_Date", DbType="NVarChar(50)")]
		public string Travel_Expense_Date
		{
			get
			{
				return this._Travel_Expense_Date;
			}
			set
			{
				if ((this._Travel_Expense_Date != value))
				{
					this._Travel_Expense_Date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VenueName", DbType="NVarChar(100)")]
		public string VenueName
		{
			get
			{
				return this._VenueName;
			}
			set
			{
				if ((this._VenueName != value))
				{
					this._VenueName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VenueAddress1", DbType="NVarChar(100)")]
		public string VenueAddress1
		{
			get
			{
				return this._VenueAddress1;
			}
			set
			{
				if ((this._VenueAddress1 != value))
				{
					this._VenueAddress1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VenueAddress2", DbType="NVarChar(100)")]
		public string VenueAddress2
		{
			get
			{
				return this._VenueAddress2;
			}
			set
			{
				if ((this._VenueAddress2 != value))
				{
					this._VenueAddress2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VenueCity", DbType="NVarChar(100)")]
		public string VenueCity
		{
			get
			{
				return this._VenueCity;
			}
			set
			{
				if ((this._VenueCity != value))
				{
					this._VenueCity = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VenueState", DbType="NVarChar(50)")]
		public string VenueState
		{
			get
			{
				return this._VenueState;
			}
			set
			{
				if ((this._VenueState != value))
				{
					this._VenueState = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VenueZip", DbType="NVarChar(50)")]
		public string VenueZip
		{
			get
			{
				return this._VenueZip;
			}
			set
			{
				if ((this._VenueZip != value))
				{
					this._VenueZip = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VenuePhone", DbType="NVarChar(50)")]
		public string VenuePhone
		{
			get
			{
				return this._VenuePhone;
			}
			set
			{
				if ((this._VenuePhone != value))
				{
					this._VenuePhone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VenueContact", DbType="NVarChar(100)")]
		public string VenueContact
		{
			get
			{
				return this._VenueContact;
			}
			set
			{
				if ((this._VenueContact != value))
				{
					this._VenueContact = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HEadCount", DbType="NVarChar(50)")]
		public string HEadCount
		{
			get
			{
				return this._HEadCount;
			}
			set
			{
				if ((this._HEadCount != value))
				{
					this._HEadCount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Total F&B]", Storage="_Total_F_B", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Total_F_B
		{
			get
			{
				return this._Total_F_B;
			}
			set
			{
				if ((this._Total_F_B != value))
				{
					this._Total_F_B = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoomCharge", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> RoomCharge
		{
			get
			{
				return this._RoomCharge;
			}
			set
			{
				if ((this._RoomCharge != value))
				{
					this._RoomCharge = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[VenueA/VCost]", Storage="_VenueA_VCost", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> VenueA_VCost
		{
			get
			{
				return this._VenueA_VCost;
			}
			set
			{
				if ((this._VenueA_VCost != value))
				{
					this._VenueA_VCost = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[A/V]", Storage="_A_V", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> A_V
		{
			get
			{
				return this._A_V;
			}
			set
			{
				if ((this._A_V != value))
				{
					this._A_V = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvitationPDFUploaded", DbType="NVarChar(50)")]
		public string InvitationPDFUploaded
		{
			get
			{
				return this._InvitationPDFUploaded;
			}
			set
			{
				if ((this._InvitationPDFUploaded != value))
				{
					this._InvitationPDFUploaded = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdditionalReqMeetingDate", DbType="NVarChar(50)")]
		public string AdditionalReqMeetingDate
		{
			get
			{
				return this._AdditionalReqMeetingDate;
			}
			set
			{
				if ((this._AdditionalReqMeetingDate != value))
				{
					this._AdditionalReqMeetingDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DomeManagerCellPhone", DbType="NVarChar(50)")]
		public string DomeManagerCellPhone
		{
			get
			{
				return this._DomeManagerCellPhone;
			}
			set
			{
				if ((this._DomeManagerCellPhone != value))
				{
					this._DomeManagerCellPhone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Parking", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Parking
		{
			get
			{
				return this._Parking;
			}
			set
			{
				if ((this._Parking != value))
				{
					this._Parking = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Accounting", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Accounting
		{
			get
			{
				return this._Accounting;
			}
			set
			{
				if ((this._Accounting != value))
				{
					this._Accounting = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_invite_qty", DbType="NVarChar(50)")]
		public string invite_qty
		{
			get
			{
				return this._invite_qty;
			}
			set
			{
				if ((this._invite_qty != value))
				{
					this._invite_qty = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Invite", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Invite
		{
			get
			{
				return this._Invite;
			}
			set
			{
				if ((this._Invite != value))
				{
					this._Invite = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Fed Ex]", Storage="_Fed_Ex", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Fed_Ex
		{
			get
			{
				return this._Fed_Ex;
			}
			set
			{
				if ((this._Fed_Ex != value))
				{
					this._Fed_Ex = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WebEventifCancelled1", DbType="NVarChar(500)")]
		public string WebEventifCancelled1
		{
			get
			{
				return this._WebEventifCancelled1;
			}
			set
			{
				if ((this._WebEventifCancelled1 != value))
				{
					this._WebEventifCancelled1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WebExpense", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> WebExpense
		{
			get
			{
				return this._WebExpense;
			}
			set
			{
				if ((this._WebExpense != value))
				{
					this._WebExpense = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WebProduction", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> WebProduction
		{
			get
			{
				return this._WebProduction;
			}
			set
			{
				if ((this._WebProduction != value))
				{
					this._WebProduction = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThirdRequestDate", DbType="NVarChar(50)")]
		public string ThirdRequestDate
		{
			get
			{
				return this._ThirdRequestDate;
			}
			set
			{
				if ((this._ThirdRequestDate != value))
				{
					this._ThirdRequestDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Event Mgt Svcs]", Storage="_Event_Mgt_Svcs", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Event_Mgt_Svcs
		{
			get
			{
				return this._Event_Mgt_Svcs;
			}
			set
			{
				if ((this._Event_Mgt_Svcs != value))
				{
					this._Event_Mgt_Svcs = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Meal", DbType="NVarChar(50)")]
		public string Meal
		{
			get
			{
				return this._Meal;
			}
			set
			{
				if ((this._Meal != value))
				{
					this._Meal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Presentation Title]", Storage="_Presentation_Title", DbType="NVarChar(1000)")]
		public string Presentation_Title
		{
			get
			{
				return this._Presentation_Title;
			}
			set
			{
				if ((this._Presentation_Title != value))
				{
					this._Presentation_Title = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[preconfirmed speaker]", Storage="_preconfirmed_speaker", DbType="NVarChar(200)")]
		public string preconfirmed_speaker
		{
			get
			{
				return this._preconfirmed_speaker;
			}
			set
			{
				if ((this._preconfirmed_speaker != value))
				{
					this._preconfirmed_speaker = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[preconfirmed meeting date]", Storage="_preconfirmed_meeting_date", DbType="NVarChar(50)")]
		public string preconfirmed_meeting_date
		{
			get
			{
				return this._preconfirmed_meeting_date;
			}
			set
			{
				if ((this._preconfirmed_meeting_date != value))
				{
					this._preconfirmed_meeting_date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Financial Notes]", Storage="_Financial_Notes", DbType="NVarChar(MAX)")]
		public string Financial_Notes
		{
			get
			{
				return this._Financial_Notes;
			}
			set
			{
				if ((this._Financial_Notes != value))
				{
					this._Financial_Notes = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[program details upload]", Storage="_program_details_upload", DbType="NVarChar(50)")]
		public string program_details_upload
		{
			get
			{
				return this._program_details_upload;
			}
			set
			{
				if ((this._program_details_upload != value))
				{
					this._program_details_upload = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[attendee upload]", Storage="_attendee_upload", DbType="NVarChar(50)")]
		public string attendee_upload
		{
			get
			{
				return this._attendee_upload;
			}
			set
			{
				if ((this._attendee_upload != value))
				{
					this._attendee_upload = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[speaker upload]", Storage="_speaker_upload", DbType="NVarChar(50)")]
		public string speaker_upload
		{
			get
			{
				return this._speaker_upload;
			}
			set
			{
				if ((this._speaker_upload != value))
				{
					this._speaker_upload = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Apex Job Number]", Storage="_Apex_Job_Number", DbType="NVarChar(50)")]
		public string Apex_Job_Number
		{
			get
			{
				return this._Apex_Job_Number;
			}
			set
			{
				if ((this._Apex_Job_Number != value))
				{
					this._Apex_Job_Number = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Check Number Fee]", Storage="_Check_Number_Fee", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Check_Number_Fee
		{
			get
			{
				return this._Check_Number_Fee;
			}
			set
			{
				if ((this._Check_Number_Fee != value))
				{
					this._Check_Number_Fee = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Check Number Travel]", Storage="_Check_Number_Travel", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Check_Number_Travel
		{
			get
			{
				return this._Check_Number_Travel;
			}
			set
			{
				if ((this._Check_Number_Travel != value))
				{
					this._Check_Number_Travel = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Number of rehearsals]", Storage="_Number_of_rehearsals", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Number_of_rehearsals
		{
			get
			{
				return this._Number_of_rehearsals;
			}
			set
			{
				if ((this._Number_of_rehearsals != value))
				{
					this._Number_of_rehearsals = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[OIG Check date speaker bureau]", Storage="_OIG_Check_date_speaker_bureau", DbType="DateTime")]
		public System.Nullable<System.DateTime> OIG_Check_date_speaker_bureau
		{
			get
			{
				return this._OIG_Check_date_speaker_bureau;
			}
			set
			{
				if ((this._OIG_Check_date_speaker_bureau != value))
				{
					this._OIG_Check_date_speaker_bureau = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[EPLS Check date speaker bureau]", Storage="_EPLS_Check_date_speaker_bureau", DbType="DateTime")]
		public System.Nullable<System.DateTime> EPLS_Check_date_speaker_bureau
		{
			get
			{
				return this._EPLS_Check_date_speaker_bureau;
			}
			set
			{
				if ((this._EPLS_Check_date_speaker_bureau != value))
				{
					this._EPLS_Check_date_speaker_bureau = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[FDAdebarment_speaker bureau]", Storage="_FDAdebarment_speaker_bureau", DbType="NVarChar(50)")]
		public string FDAdebarment_speaker_bureau
		{
			get
			{
				return this._FDAdebarment_speaker_bureau;
			}
			set
			{
				if ((this._FDAdebarment_speaker_bureau != value))
				{
					this._FDAdebarment_speaker_bureau = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Region", DbType="NVarChar(50)")]
		public string Region
		{
			get
			{
				return this._Region;
			}
			set
			{
				if ((this._Region != value))
				{
					this._Region = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[If cancelled, Travel1]", Storage="_If_cancelled__Travel1", DbType="NVarChar(500)")]
		public string If_cancelled__Travel1
		{
			get
			{
				return this._If_cancelled__Travel1;
			}
			set
			{
				if ((this._If_cancelled__Travel1 != value))
				{
					this._If_cancelled__Travel1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[If cancelled, Travel2]", Storage="_If_cancelled__Travel2", DbType="NVarChar(500)")]
		public string If_cancelled__Travel2
		{
			get
			{
				return this._If_cancelled__Travel2;
			}
			set
			{
				if ((this._If_cancelled__Travel2 != value))
				{
					this._If_cancelled__Travel2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[If cancelled, Travel3]", Storage="_If_cancelled__Travel3", DbType="NVarChar(500)")]
		public string If_cancelled__Travel3
		{
			get
			{
				return this._If_cancelled__Travel3;
			}
			set
			{
				if ((this._If_cancelled__Travel3 != value))
				{
					this._If_cancelled__Travel3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Any reason for cancel1]", Storage="_Any_reason_for_cancel1", DbType="NVarChar(500)")]
		public string Any_reason_for_cancel1
		{
			get
			{
				return this._Any_reason_for_cancel1;
			}
			set
			{
				if ((this._Any_reason_for_cancel1 != value))
				{
					this._Any_reason_for_cancel1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Invitations Mailed]", Storage="_Invitations_Mailed", DbType="NVarChar(50)")]
		public string Invitations_Mailed
		{
			get
			{
				return this._Invitations_Mailed;
			}
			set
			{
				if ((this._Invitations_Mailed != value))
				{
					this._Invitations_Mailed = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_invite_qty2", DbType="NVarChar(50)")]
		public string invite_qty2
		{
			get
			{
				return this._invite_qty2;
			}
			set
			{
				if ((this._invite_qty2 != value))
				{
					this._invite_qty2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_invite2", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> invite2
		{
			get
			{
				return this._invite2;
			}
			set
			{
				if ((this._invite2 != value))
				{
					this._invite2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Dual Speaker]", Storage="_Dual_Speaker", DbType="VarChar(1000)")]
		public string Dual_Speaker
		{
			get
			{
				return this._Dual_Speaker;
			}
			set
			{
				if ((this._Dual_Speaker != value))
				{
					this._Dual_Speaker = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Dual Speaker Fee]", Storage="_Dual_Speaker_Fee", DbType="NVarChar(50)")]
		public string Dual_Speaker_Fee
		{
			get
			{
				return this._Dual_Speaker_Fee;
			}
			set
			{
				if ((this._Dual_Speaker_Fee != value))
				{
					this._Dual_Speaker_Fee = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Dual Speaker Expenses]", Storage="_Dual_Speaker_Expenses", DbType="NVarChar(50)")]
		public string Dual_Speaker_Expenses
		{
			get
			{
				return this._Dual_Speaker_Expenses;
			}
			set
			{
				if ((this._Dual_Speaker_Expenses != value))
				{
					this._Dual_Speaker_Expenses = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Dual Speaker Air]", Storage="_Dual_Speaker_Air", DbType="NVarChar(50)")]
		public string Dual_Speaker_Air
		{
			get
			{
				return this._Dual_Speaker_Air;
			}
			set
			{
				if ((this._Dual_Speaker_Air != value))
				{
					this._Dual_Speaker_Air = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Dual Speaker Hotel]", Storage="_Dual_Speaker_Hotel", DbType="NVarChar(50)")]
		public string Dual_Speaker_Hotel
		{
			get
			{
				return this._Dual_Speaker_Hotel;
			}
			set
			{
				if ((this._Dual_Speaker_Hotel != value))
				{
					this._Dual_Speaker_Hotel = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Dual Speaker Ground]", Storage="_Dual_Speaker_Ground", DbType="NVarChar(50)")]
		public string Dual_Speaker_Ground
		{
			get
			{
				return this._Dual_Speaker_Ground;
			}
			set
			{
				if ((this._Dual_Speaker_Ground != value))
				{
					this._Dual_Speaker_Ground = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[4thChoiceDate]", Storage="__4thChoiceDate", DbType="NVarChar(50)")]
		public string _4thChoiceDate
		{
			get
			{
				return this.@__4thChoiceDate;
			}
			set
			{
				if ((this.@__4thChoiceDate != value))
				{
					this.@__4thChoiceDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[4thchoicespeaker]", Storage="__4thchoicespeaker", DbType="NVarChar(100)")]
		public string _4thchoicespeaker
		{
			get
			{
				return this.@__4thchoicespeaker;
			}
			set
			{
				if ((this.@__4thchoicespeaker != value))
				{
					this.@__4thchoicespeaker = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[5thchoicespeaker]", Storage="__5thchoicespeaker", DbType="NVarChar(100)")]
		public string _5thchoicespeaker
		{
			get
			{
				return this.@__5thchoicespeaker;
			}
			set
			{
				if ((this.@__5thchoicespeaker != value))
				{
					this.@__5thchoicespeaker = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dualspeakerfeedateoncheck", DbType="NVarChar(50)")]
		public string dualspeakerfeedateoncheck
		{
			get
			{
				return this._dualspeakerfeedateoncheck;
			}
			set
			{
				if ((this._dualspeakerfeedateoncheck != value))
				{
					this._dualspeakerfeedateoncheck = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dualspeakerexpensesdateoncheck", DbType="NVarChar(50)")]
		public string dualspeakerexpensesdateoncheck
		{
			get
			{
				return this._dualspeakerexpensesdateoncheck;
			}
			set
			{
				if ((this._dualspeakerexpensesdateoncheck != value))
				{
					this._dualspeakerexpensesdateoncheck = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dualspeakerfeechecknumber", DbType="NVarChar(50)")]
		public string dualspeakerfeechecknumber
		{
			get
			{
				return this._dualspeakerfeechecknumber;
			}
			set
			{
				if ((this._dualspeakerfeechecknumber != value))
				{
					this._dualspeakerfeechecknumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dualspeakerexpenseschecknumber", DbType="NVarChar(50)")]
		public string dualspeakerexpenseschecknumber
		{
			get
			{
				return this._dualspeakerexpenseschecknumber;
			}
			set
			{
				if ((this._dualspeakerexpenseschecknumber != value))
				{
					this._dualspeakerexpenseschecknumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Grand Total F&B]", Storage="_Grand_Total_F_B", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Grand_Total_F_B
		{
			get
			{
				return this._Grand_Total_F_B;
			}
			set
			{
				if ((this._Grand_Total_F_B != value))
				{
					this._Grand_Total_F_B = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Grand Total Speaker]", Storage="_Grand_Total_Speaker", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Grand_Total_Speaker
		{
			get
			{
				return this._Grand_Total_Speaker;
			}
			set
			{
				if ((this._Grand_Total_Speaker != value))
				{
					this._Grand_Total_Speaker = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Invitation Total]", Storage="_Invitation_Total", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Invitation_Total
		{
			get
			{
				return this._Invitation_Total;
			}
			set
			{
				if ((this._Invitation_Total != value))
				{
					this._Invitation_Total = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Web Total]", Storage="_Web_Total", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Web_Total
		{
			get
			{
				return this._Web_Total;
			}
			set
			{
				if ((this._Web_Total != value))
				{
					this._Web_Total = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Total Change Costs]", Storage="_Total_Change_Costs", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Total_Change_Costs
		{
			get
			{
				return this._Total_Change_Costs;
			}
			set
			{
				if ((this._Total_Change_Costs != value))
				{
					this._Total_Change_Costs = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Total Cancellation Costs]", Storage="_Total_Cancellation_Costs", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Total_Cancellation_Costs
		{
			get
			{
				return this._Total_Cancellation_Costs;
			}
			set
			{
				if ((this._Total_Cancellation_Costs != value))
				{
					this._Total_Cancellation_Costs = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Last Edited]", Storage="_Last_Edited", DbType="DateTime")]
		public System.Nullable<System.DateTime> Last_Edited
		{
			get
			{
				return this._Last_Edited;
			}
			set
			{
				if ((this._Last_Edited != value))
				{
					this._Last_Edited = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[All Costs for Program Entered]", Storage="_All_Costs_for_Program_Entered", DbType="VarChar(50)")]
		public string All_Costs_for_Program_Entered
		{
			get
			{
				return this._All_Costs_for_Program_Entered;
			}
			set
			{
				if ((this._All_Costs_for_Program_Entered != value))
				{
					this._All_Costs_for_Program_Entered = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Totality Uploaded]", Storage="_Totality_Uploaded", DbType="VarChar(50)")]
		public string Totality_Uploaded
		{
			get
			{
				return this._Totality_Uploaded;
			}
			set
			{
				if ((this._Totality_Uploaded != value))
				{
					this._Totality_Uploaded = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LDC_Phone", DbType="VarChar(50)")]
		public string LDC_Phone
		{
			get
			{
				return this._LDC_Phone;
			}
			set
			{
				if ((this._LDC_Phone != value))
				{
					this._LDC_Phone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LDC_Email", DbType="VarChar(100)")]
		public string LDC_Email
		{
			get
			{
				return this._LDC_Email;
			}
			set
			{
				if ((this._LDC_Email != value))
				{
					this._LDC_Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[venue cancellation fee]", Storage="_venue_cancellation_fee", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> venue_cancellation_fee
		{
			get
			{
				return this._venue_cancellation_fee;
			}
			set
			{
				if ((this._venue_cancellation_fee != value))
				{
					this._venue_cancellation_fee = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[CWT Transaction Fee]", Storage="_CWT_Transaction_Fee", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> CWT_Transaction_Fee
		{
			get
			{
				return this._CWT_Transaction_Fee;
			}
			set
			{
				if ((this._CWT_Transaction_Fee != value))
				{
					this._CWT_Transaction_Fee = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[CWT Transaction Fee Changes]", Storage="_CWT_Transaction_Fee_Changes", DbType="VarChar(1)")]
		public string CWT_Transaction_Fee_Changes
		{
			get
			{
				return this._CWT_Transaction_Fee_Changes;
			}
			set
			{
				if ((this._CWT_Transaction_Fee_Changes != value))
				{
					this._CWT_Transaction_Fee_Changes = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Train Expense]", Storage="_Train_Expense", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Train_Expense
		{
			get
			{
				return this._Train_Expense;
			}
			set
			{
				if ((this._Train_Expense != value))
				{
					this._Train_Expense = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[CWT Transaction Fee Ground]", Storage="_CWT_Transaction_Fee_Ground", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> CWT_Transaction_Fee_Ground
		{
			get
			{
				return this._CWT_Transaction_Fee_Ground;
			}
			set
			{
				if ((this._CWT_Transaction_Fee_Ground != value))
				{
					this._CWT_Transaction_Fee_Ground = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[CWT Transaction Fee Hotel]", Storage="_CWT_Transaction_Fee_Hotel", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> CWT_Transaction_Fee_Hotel
		{
			get
			{
				return this._CWT_Transaction_Fee_Hotel;
			}
			set
			{
				if ((this._CWT_Transaction_Fee_Hotel != value))
				{
					this._CWT_Transaction_Fee_Hotel = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[CWT Transaction Fee Changes Ground]", Storage="_CWT_Transaction_Fee_Changes_Ground", DbType="VarChar(1)")]
		public string CWT_Transaction_Fee_Changes_Ground
		{
			get
			{
				return this._CWT_Transaction_Fee_Changes_Ground;
			}
			set
			{
				if ((this._CWT_Transaction_Fee_Changes_Ground != value))
				{
					this._CWT_Transaction_Fee_Changes_Ground = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[CWT Transaction Fee Changes Hotel]", Storage="_CWT_Transaction_Fee_Changes_Hotel", DbType="VarChar(1)")]
		public string CWT_Transaction_Fee_Changes_Hotel
		{
			get
			{
				return this._CWT_Transaction_Fee_Changes_Hotel;
			}
			set
			{
				if ((this._CWT_Transaction_Fee_Changes_Hotel != value))
				{
					this._CWT_Transaction_Fee_Changes_Hotel = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[CWT Transaction Fee Total]", Storage="_CWT_Transaction_Fee_Total", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> CWT_Transaction_Fee_Total
		{
			get
			{
				return this._CWT_Transaction_Fee_Total;
			}
			set
			{
				if ((this._CWT_Transaction_Fee_Total != value))
				{
					this._CWT_Transaction_Fee_Total = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Confirmed Speaker Phone]", Storage="_Confirmed_Speaker_Phone", DbType="VarChar(255)")]
		public string Confirmed_Speaker_Phone
		{
			get
			{
				return this._Confirmed_Speaker_Phone;
			}
			set
			{
				if ((this._Confirmed_Speaker_Phone != value))
				{
					this._Confirmed_Speaker_Phone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Confirmed Speaker Email]", Storage="_Confirmed_Speaker_Email", DbType="VarChar(255)")]
		public string Confirmed_Speaker_Email
		{
			get
			{
				return this._Confirmed_Speaker_Email;
			}
			set
			{
				if ((this._Confirmed_Speaker_Email != value))
				{
					this._Confirmed_Speaker_Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Venue Receipt Received]", Storage="_Venue_Receipt_Received", DbType="VarChar(3)")]
		public string Venue_Receipt_Received
		{
			get
			{
				return this._Venue_Receipt_Received;
			}
			set
			{
				if ((this._Venue_Receipt_Received != value))
				{
					this._Venue_Receipt_Received = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Attendee Checklist Received]", Storage="_Attendee_Checklist_Received", DbType="DateTime")]
		public System.Nullable<System.DateTime> Attendee_Checklist_Received
		{
			get
			{
				return this._Attendee_Checklist_Received;
			}
			set
			{
				if ((this._Attendee_Checklist_Received != value))
				{
					this._Attendee_Checklist_Received = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Attendees served]", Storage="_Attendees_served", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Attendees_served
		{
			get
			{
				return this._Attendees_served;
			}
			set
			{
				if ((this._Attendees_served != value))
				{
					this._Attendees_served = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Cost per attendee]", Storage="_Cost_per_attendee", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Cost_per_attendee
		{
			get
			{
				return this._Cost_per_attendee;
			}
			set
			{
				if ((this._Cost_per_attendee != value))
				{
					this._Cost_per_attendee = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Totalityneeded", DbType="NChar(10)")]
		public string Totalityneeded
		{
			get
			{
				return this._Totalityneeded;
			}
			set
			{
				if ((this._Totalityneeded != value))
				{
					this._Totalityneeded = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_signinsheetuploaded", DbType="DateTime")]
		public System.Nullable<System.DateTime> signinsheetuploaded
		{
			get
			{
				return this._signinsheetuploaded;
			}
			set
			{
				if ((this._signinsheetuploaded != value))
				{
					this._signinsheetuploaded = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[folder received]", Storage="_folder_received", DbType="DateTime")]
		public System.Nullable<System.DateTime> folder_received
		{
			get
			{
				return this._folder_received;
			}
			set
			{
				if ((this._folder_received != value))
				{
					this._folder_received = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[totality completed by]", Storage="_totality_completed_by", DbType="VarChar(100)")]
		public string totality_completed_by
		{
			get
			{
				return this._totality_completed_by;
			}
			set
			{
				if ((this._totality_completed_by != value))
				{
					this._totality_completed_by = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cancel_email_requested", DbType="VarChar(50)")]
		public string cancel_email_requested
		{
			get
			{
				return this._cancel_email_requested;
			}
			set
			{
				if ((this._cancel_email_requested != value))
				{
					this._cancel_email_requested = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CardRequested", DbType="VarChar(100)")]
		public string CardRequested
		{
			get
			{
				return this._CardRequested;
			}
			set
			{
				if ((this._CardRequested != value))
				{
					this._CardRequested = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CardNumber", DbType="VarChar(100)")]
		public string CardNumber
		{
			get
			{
				return this._CardNumber;
			}
			set
			{
				if ((this._CardNumber != value))
				{
					this._CardNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CardImage", DbType="VarChar(200)")]
		public string CardImage
		{
			get
			{
				return this._CardImage;
			}
			set
			{
				if ((this._CardImage != value))
				{
					this._CardImage = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CardImageBack", DbType="VarChar(200)")]
		public string CardImageBack
		{
			get
			{
				return this._CardImageBack;
			}
			set
			{
				if ((this._CardImageBack != value))
				{
					this._CardImageBack = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EndTime", DbType="NVarChar(50)")]
		public string EndTime
		{
			get
			{
				return this._EndTime;
			}
			set
			{
				if ((this._EndTime != value))
				{
					this._EndTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EndTimeZone", DbType="NVarChar(50)")]
		public string EndTimeZone
		{
			get
			{
				return this._EndTimeZone;
			}
			set
			{
				if ((this._EndTimeZone != value))
				{
					this._EndTimeZone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[apex fax number]", Storage="_apex_fax_number", DbType="VarChar(50)")]
		public string apex_fax_number
		{
			get
			{
				return this._apex_fax_number;
			}
			set
			{
				if ((this._apex_fax_number != value))
				{
					this._apex_fax_number = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DMTitle", DbType="VarChar(500)")]
		public string DMTitle
		{
			get
			{
				return this._DMTitle;
			}
			set
			{
				if ((this._DMTitle != value))
				{
					this._DMTitle = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_checkrequest", DbType="VarChar(100)")]
		public string checkrequest
		{
			get
			{
				return this._checkrequest;
			}
			set
			{
				if ((this._checkrequest != value))
				{
					this._checkrequest = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Booked via Get There]", Storage="_Booked_via_Get_There", DbType="VarChar(1)")]
		public string Booked_via_Get_There
		{
			get
			{
				return this._Booked_via_Get_There;
			}
			set
			{
				if ((this._Booked_via_Get_There != value))
				{
					this._Booked_via_Get_There = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Dual Speaker Phone]", Storage="_Dual_Speaker_Phone", DbType="VarChar(100)")]
		public string Dual_Speaker_Phone
		{
			get
			{
				return this._Dual_Speaker_Phone;
			}
			set
			{
				if ((this._Dual_Speaker_Phone != value))
				{
					this._Dual_Speaker_Phone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Dual Speaker Email]", Storage="_Dual_Speaker_Email", DbType="VarChar(100)")]
		public string Dual_Speaker_Email
		{
			get
			{
				return this._Dual_Speaker_Email;
			}
			set
			{
				if ((this._Dual_Speaker_Email != value))
				{
					this._Dual_Speaker_Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[CWT2 Transaction Fee Changes Ground]", Storage="_CWT2_Transaction_Fee_Changes_Ground", DbType="VarChar(1)")]
		public string CWT2_Transaction_Fee_Changes_Ground
		{
			get
			{
				return this._CWT2_Transaction_Fee_Changes_Ground;
			}
			set
			{
				if ((this._CWT2_Transaction_Fee_Changes_Ground != value))
				{
					this._CWT2_Transaction_Fee_Changes_Ground = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[CWT2 Transaction Fee Changes]", Storage="_CWT2_Transaction_Fee_Changes", DbType="VarChar(1)")]
		public string CWT2_Transaction_Fee_Changes
		{
			get
			{
				return this._CWT2_Transaction_Fee_Changes;
			}
			set
			{
				if ((this._CWT2_Transaction_Fee_Changes != value))
				{
					this._CWT2_Transaction_Fee_Changes = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[CWT2 Transaction Fee Ground]", Storage="_CWT2_Transaction_Fee_Ground", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> CWT2_Transaction_Fee_Ground
		{
			get
			{
				return this._CWT2_Transaction_Fee_Ground;
			}
			set
			{
				if ((this._CWT2_Transaction_Fee_Ground != value))
				{
					this._CWT2_Transaction_Fee_Ground = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[CWT2 Transaction Fee Total]", Storage="_CWT2_Transaction_Fee_Total", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> CWT2_Transaction_Fee_Total
		{
			get
			{
				return this._CWT2_Transaction_Fee_Total;
			}
			set
			{
				if ((this._CWT2_Transaction_Fee_Total != value))
				{
					this._CWT2_Transaction_Fee_Total = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[CWT2 Transaction Fee]", Storage="_CWT2_Transaction_Fee", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> CWT2_Transaction_Fee
		{
			get
			{
				return this._CWT2_Transaction_Fee;
			}
			set
			{
				if ((this._CWT2_Transaction_Fee != value))
				{
					this._CWT2_Transaction_Fee = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_domelink", DbType="VarChar(255)")]
		public string domelink
		{
			get
			{
				return this._domelink;
			}
			set
			{
				if ((this._domelink != value))
				{
					this._domelink = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vipdialin", DbType="VarChar(255)")]
		public string vipdialin
		{
			get
			{
				return this._vipdialin;
			}
			set
			{
				if ((this._vipdialin != value))
				{
					this._vipdialin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_participantdialin", DbType="VarChar(255)")]
		public string participantdialin
		{
			get
			{
				return this._participantdialin;
			}
			set
			{
				if ((this._participantdialin != value))
				{
					this._participantdialin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_inviteprint2", DbType="NChar(10)")]
		public string inviteprint2
		{
			get
			{
				return this._inviteprint2;
			}
			set
			{
				if ((this._inviteprint2 != value))
				{
					this._inviteprint2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_inviteprint3", DbType="NChar(10)")]
		public string inviteprint3
		{
			get
			{
				return this._inviteprint3;
			}
			set
			{
				if ((this._inviteprint3 != value))
				{
					this._inviteprint3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_domemgremail", DbType="VarChar(100)")]
		public string domemgremail
		{
			get
			{
				return this._domemgremail;
			}
			set
			{
				if ((this._domemgremail != value))
				{
					this._domemgremail = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Presentation Time]", Storage="_Presentation_Time", DbType="VarChar(100)")]
		public string Presentation_Time
		{
			get
			{
				return this._Presentation_Time;
			}
			set
			{
				if ((this._Presentation_Time != value))
				{
					this._Presentation_Time = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Meal and Presentation Type]", Storage="_Meal_and_Presentation_Type", DbType="VarChar(100)")]
		public string Meal_and_Presentation_Type
		{
			get
			{
				return this._Meal_and_Presentation_Type;
			}
			set
			{
				if ((this._Meal_and_Presentation_Type != value))
				{
					this._Meal_and_Presentation_Type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Confirmed Date for Invite]", Storage="_Confirmed_Date_for_Invite", DbType="DateTime")]
		public System.Nullable<System.DateTime> Confirmed_Date_for_Invite
		{
			get
			{
				return this._Confirmed_Date_for_Invite;
			}
			set
			{
				if ((this._Confirmed_Date_for_Invite != value))
				{
					this._Confirmed_Date_for_Invite = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WebEventifCancelled2", DbType="NVarChar(500)")]
		public string WebEventifCancelled2
		{
			get
			{
				return this._WebEventifCancelled2;
			}
			set
			{
				if ((this._WebEventifCancelled2 != value))
				{
					this._WebEventifCancelled2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WebEventifCancelled3", DbType="NVarChar(500)")]
		public string WebEventifCancelled3
		{
			get
			{
				return this._WebEventifCancelled3;
			}
			set
			{
				if ((this._WebEventifCancelled3 != value))
				{
					this._WebEventifCancelled3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Any reason for cancel2]", Storage="_Any_reason_for_cancel2", DbType="NVarChar(500)")]
		public string Any_reason_for_cancel2
		{
			get
			{
				return this._Any_reason_for_cancel2;
			}
			set
			{
				if ((this._Any_reason_for_cancel2 != value))
				{
					this._Any_reason_for_cancel2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Any reason for cancel3]", Storage="_Any_reason_for_cancel3", DbType="NVarChar(500)")]
		public string Any_reason_for_cancel3
		{
			get
			{
				return this._Any_reason_for_cancel3;
			}
			set
			{
				if ((this._Any_reason_for_cancel3 != value))
				{
					this._Any_reason_for_cancel3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Totality", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Totality
		{
			get
			{
				return this._Totality;
			}
			set
			{
				if ((this._Totality != value))
				{
					this._Totality = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[CWT2 Transaction Fee Hotel]", Storage="_CWT2_Transaction_Fee_Hotel", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> CWT2_Transaction_Fee_Hotel
		{
			get
			{
				return this._CWT2_Transaction_Fee_Hotel;
			}
			set
			{
				if ((this._CWT2_Transaction_Fee_Hotel != value))
				{
					this._CWT2_Transaction_Fee_Hotel = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[CWT2 Transaction Fee Changes Hotel]", Storage="_CWT2_Transaction_Fee_Changes_Hotel", DbType="VarChar(1)")]
		public string CWT2_Transaction_Fee_Changes_Hotel
		{
			get
			{
				return this._CWT2_Transaction_Fee_Changes_Hotel;
			}
			set
			{
				if ((this._CWT2_Transaction_Fee_Changes_Hotel != value))
				{
					this._CWT2_Transaction_Fee_Changes_Hotel = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[2ndChoiceDate]", Storage="__2ndChoiceDate", DbType="NVarChar(50)")]
		public string _2ndChoiceDate
		{
			get
			{
				return this.@__2ndChoiceDate;
			}
			set
			{
				if ((this.@__2ndChoiceDate != value))
				{
					this.@__2ndChoiceDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[3rdChoiceDate]", Storage="__3rdChoiceDate", DbType="NVarChar(50)")]
		public string _3rdChoiceDate
		{
			get
			{
				return this.@__3rdChoiceDate;
			}
			set
			{
				if ((this.@__3rdChoiceDate != value))
				{
					this.@__3rdChoiceDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Service Vendor Fee]", Storage="_Service_Vendor_Fee", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Service_Vendor_Fee
		{
			get
			{
				return this._Service_Vendor_Fee;
			}
			set
			{
				if ((this._Service_Vendor_Fee != value))
				{
					this._Service_Vendor_Fee = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_inviteprint1", DbType="NChar(10)")]
		public string inviteprint1
		{
			get
			{
				return this._inviteprint1;
			}
			set
			{
				if ((this._inviteprint1 != value))
				{
					this._inviteprint1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ConfirmedSpeakerDate", DbType="NVarChar(50)")]
		public string ConfirmedSpeakerDate
		{
			get
			{
				return this._ConfirmedSpeakerDate;
			}
			set
			{
				if ((this._ConfirmedSpeakerDate != value))
				{
					this._ConfirmedSpeakerDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_franchise", DbType="VarChar(50)")]
		public string franchise
		{
			get
			{
				return this._franchise;
			}
			set
			{
				if ((this._franchise != value))
				{
					this._franchise = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[meeting format]", Storage="_meeting_format", DbType="VarChar(50)")]
		public string meeting_format
		{
			get
			{
				return this._meeting_format;
			}
			set
			{
				if ((this._meeting_format != value))
				{
					this._meeting_format = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[meal type]", Storage="_meal_type", DbType="VarChar(50)")]
		public string meal_type
		{
			get
			{
				return this._meal_type;
			}
			set
			{
				if ((this._meal_type != value))
				{
					this._meal_type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[location type]", Storage="_location_type", DbType="VarChar(50)")]
		public string location_type
		{
			get
			{
				return this._location_type;
			}
			set
			{
				if ((this._location_type != value))
				{
					this._location_type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[non compliant venue]", Storage="_non_compliant_venue", DbType="VarChar(5)")]
		public string non_compliant_venue
		{
			get
			{
				return this._non_compliant_venue;
			}
			set
			{
				if ((this._non_compliant_venue != value))
				{
					this._non_compliant_venue = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[venue contact email]", Storage="_venue_contact_email", DbType="VarChar(75)")]
		public string venue_contact_email
		{
			get
			{
				return this._venue_contact_email;
			}
			set
			{
				if ((this._venue_contact_email != value))
				{
					this._venue_contact_email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[fedex tracking invitations]", Storage="_fedex_tracking_invitations", DbType="VarChar(50)")]
		public string fedex_tracking_invitations
		{
			get
			{
				return this._fedex_tracking_invitations;
			}
			set
			{
				if ((this._fedex_tracking_invitations != value))
				{
					this._fedex_tracking_invitations = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[fedex tracking in office]", Storage="_fedex_tracking_in_office", DbType="VarChar(50)")]
		public string fedex_tracking_in_office
		{
			get
			{
				return this._fedex_tracking_in_office;
			}
			set
			{
				if ((this._fedex_tracking_in_office != value))
				{
					this._fedex_tracking_in_office = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[date in office shipment mailed]", Storage="_date_in_office_shipment_mailed", DbType="DateTime")]
		public System.Nullable<System.DateTime> date_in_office_shipment_mailed
		{
			get
			{
				return this._date_in_office_shipment_mailed;
			}
			set
			{
				if ((this._date_in_office_shipment_mailed != value))
				{
					this._date_in_office_shipment_mailed = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[additional shipments notes]", Storage="_additional_shipments_notes", DbType="VarChar(MAX)")]
		public string additional_shipments_notes
		{
			get
			{
				return this._additional_shipments_notes;
			}
			set
			{
				if ((this._additional_shipments_notes != value))
				{
					this._additional_shipments_notes = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[unmet minimum]", Storage="_unmet_minimum", DbType="VarChar(50)")]
		public string unmet_minimum
		{
			get
			{
				return this._unmet_minimum;
			}
			set
			{
				if ((this._unmet_minimum != value))
				{
					this._unmet_minimum = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[no of guaranteed attendees]", Storage="_no_of_guaranteed_attendees", DbType="VarChar(50)")]
		public string no_of_guaranteed_attendees
		{
			get
			{
				return this._no_of_guaranteed_attendees;
			}
			set
			{
				if ((this._no_of_guaranteed_attendees != value))
				{
					this._no_of_guaranteed_attendees = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[fedex tracking speaker fee]", Storage="_fedex_tracking_speaker_fee", DbType="VarChar(50)")]
		public string fedex_tracking_speaker_fee
		{
			get
			{
				return this._fedex_tracking_speaker_fee;
			}
			set
			{
				if ((this._fedex_tracking_speaker_fee != value))
				{
					this._fedex_tracking_speaker_fee = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[fedex tracking speaker expense]", Storage="_fedex_tracking_speaker_expense", DbType="VarChar(50)")]
		public string fedex_tracking_speaker_expense
		{
			get
			{
				return this._fedex_tracking_speaker_expense;
			}
			set
			{
				if ((this._fedex_tracking_speaker_expense != value))
				{
					this._fedex_tracking_speaker_expense = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[date submitted for totality]", Storage="_date_submitted_for_totality", DbType="DateTime")]
		public System.Nullable<System.DateTime> date_submitted_for_totality
		{
			get
			{
				return this._date_submitted_for_totality;
			}
			set
			{
				if ((this._date_submitted_for_totality != value))
				{
					this._date_submitted_for_totality = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[fedex tracking speaker fee rheum]", Storage="_fedex_tracking_speaker_fee_rheum", DbType="VarChar(50)")]
		public string fedex_tracking_speaker_fee_rheum
		{
			get
			{
				return this._fedex_tracking_speaker_fee_rheum;
			}
			set
			{
				if ((this._fedex_tracking_speaker_fee_rheum != value))
				{
					this._fedex_tracking_speaker_fee_rheum = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[fedex tracking speaker expense rheum]", Storage="_fedex_tracking_speaker_expense_rheum", DbType="VarChar(50)")]
		public string fedex_tracking_speaker_expense_rheum
		{
			get
			{
				return this._fedex_tracking_speaker_expense_rheum;
			}
			set
			{
				if ((this._fedex_tracking_speaker_expense_rheum != value))
				{
					this._fedex_tracking_speaker_expense_rheum = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[fedex tracking dual speaker fee]", Storage="_fedex_tracking_dual_speaker_fee", DbType="VarChar(50)")]
		public string fedex_tracking_dual_speaker_fee
		{
			get
			{
				return this._fedex_tracking_dual_speaker_fee;
			}
			set
			{
				if ((this._fedex_tracking_dual_speaker_fee != value))
				{
					this._fedex_tracking_dual_speaker_fee = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[fedex tracking dual speaker expense]", Storage="_fedex_tracking_dual_speaker_expense", DbType="VarChar(50)")]
		public string fedex_tracking_dual_speaker_expense
		{
			get
			{
				return this._fedex_tracking_dual_speaker_expense;
			}
			set
			{
				if ((this._fedex_tracking_dual_speaker_expense != value))
				{
					this._fedex_tracking_dual_speaker_expense = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[based on guarantee]", Storage="_based_on_guarantee", DbType="VarChar(5)")]
		public string based_on_guarantee
		{
			get
			{
				return this._based_on_guarantee;
			}
			set
			{
				if ((this._based_on_guarantee != value))
				{
					this._based_on_guarantee = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[QC By]", Storage="_QC_By", DbType="VarChar(100)")]
		public string QC_By
		{
			get
			{
				return this._QC_By;
			}
			set
			{
				if ((this._QC_By != value))
				{
					this._QC_By = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[QC Date]", Storage="_QC_Date", DbType="DateTime")]
		public System.Nullable<System.DateTime> QC_Date
		{
			get
			{
				return this._QC_Date;
			}
			set
			{
				if ((this._QC_Date != value))
				{
					this._QC_Date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Total restaurant catering receipt]", Storage="_Total_restaurant_catering_receipt", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Total_restaurant_catering_receipt
		{
			get
			{
				return this._Total_restaurant_catering_receipt;
			}
			set
			{
				if ((this._Total_restaurant_catering_receipt != value))
				{
					this._Total_restaurant_catering_receipt = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.JB_INVITE_TRACKER")]
	public partial class JB_INVITE_TRACKER
	{
		
		private decimal _ID;
		
		private string _Apex_Job_Number;
		
		private string _NFP_Code_Janssen_ID;
		
		private string _Email;
		
		private System.Nullable<bool> _InviteSent;
		
		public JB_INVITE_TRACKER()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.Always, DbType="Decimal(18,0) NOT NULL IDENTITY", IsDbGenerated=true)]
		public decimal ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Apex Job Number]", Storage="_Apex_Job_Number", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Apex_Job_Number
		{
			get
			{
				return this._Apex_Job_Number;
			}
			set
			{
				if ((this._Apex_Job_Number != value))
				{
					this._Apex_Job_Number = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[NFP Code/Janssen ID]", Storage="_NFP_Code_Janssen_ID", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string NFP_Code_Janssen_ID
		{
			get
			{
				return this._NFP_Code_Janssen_ID;
			}
			set
			{
				if ((this._NFP_Code_Janssen_ID != value))
				{
					this._NFP_Code_Janssen_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(100)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InviteSent", DbType="Bit")]
		public System.Nullable<bool> InviteSent
		{
			get
			{
				return this._InviteSent;
			}
			set
			{
				if ((this._InviteSent != value))
				{
					this._InviteSent = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
